Добавляем реализацию.
fintech-kotlin/pavlov-cashback-service pull request #1
Opened 2020-02-25 05:32 UTC by PavlovAlexL

# Выполнено задание № 1

## В процесс было сделано:
 - добавил релаизацию интерфейсов.

## PR чеклист:
 - [ ] В Project выставлен `Tinkoff "Java to Kotlin"`
 - [ ] Добавлен label с номером домашнего задания

2020-02-25 08:47 UTC, dkotelnikov commented on src/main/kotlin/ru/tinkoff/fintech/service/notification/CardNumberMaskerImpl.kt
> +                append("#")
Раз уж у нас на руках есть maskChar, то лучше использовать его для гибкости в дальнейшем.

2020-02-25 08:49 UTC, dkotelnikov commented on src/main/kotlin/ru/tinkoff/fintech/service/notification/NotificationMessageGeneratorImpl.kt
> +        return buildString {
Можно использовать kotlin [multiline string](https://kotlinlang.org/docs/reference/basic-types.html#string-literals) Для таких кейсов инструмент наиболее подходящий.

2020-02-25 08:57 UTC, dkotelnikov commented on src/main/kotlin/ru/tinkoff/fintech/service/notification/CardNumberMaskerImpl.kt
> +        var end = end
Такое "одинаковое" именование приводит к опасной путанице в переменных, вспомогательные лучше именовать иначе. 
+ можно воспользоваться тем, что if - выражение и лишний раз не создавать мутабельных значений. [Примеры из доки.](https://kotlinlang.org/docs/reference/control-flow.html)

2020-02-25 09:15 UTC, dkotelnikov requested changes

2020-02-25 09:15 UTC, dkotelnikov commented on src/main/kotlin/ru/tinkoff/fintech/service/notification/NotificationMessageGeneratorImpl.kt
> +
+ можно всю эту историю обернуть с помощью оператора with(notificationMessageInfo) {} и дальше обращаться сразу к полям. [Ссылка на доку.](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/with.html)

2020-02-25 14:16 UTC, PavlovAlexL commented on src/main/kotlin/ru/tinkoff/fintech/service/notification/CardNumberMaskerImpl.kt
> +                append("#")
Согласен, забыл заменить, исправил.

2020-02-25 14:19 UTC, PavlovAlexL commented on src/main/kotlin/ru/tinkoff/fintech/service/notification/CardNumberMaskerImpl.kt
> +        var end = end
Поправил, но не уверен что правильно вас понял.

2020-02-25 14:19 UTC, PavlovAlexL commented on src/main/kotlin/ru/tinkoff/fintech/service/notification/CardNumberMaskerImpl.kt
> +        var end = end
это я на счет if

2020-02-25 14:19 UTC, PavlovAlexL commented on src/main/kotlin/ru/tinkoff/fintech/service/notification/NotificationMessageGeneratorImpl.kt
> +
поправил.

2020-02-25 15:18 UTC, dkotelnikov requested changes

2020-02-25 15:18 UTC, dkotelnikov commented on src/main/kotlin/ru/tinkoff/fintech/service/notification/NotificationMessageGeneratorImpl.kt
> +                    "начислен cashback в размере ${notificationMessageInfo.cashback}\n" +
Аналогично, как с name, стоит поступить и с category, transactionDate, cashback.
Плюс все-таки конкатенация не перестала быть проблемой, поэтому либо multiline, например: 
`val text = """
    |Tell me and I forget.
    |Teach me and I remember.
    |Involve me and I learn.
    |(Benjamin Franklin)
    """.trimMargin()`
взял из доки - https://kotlinlang.org/docs/reference/basic-types.html#string-literals
либо stringBuilder

2020-02-26 07:07 UTC, dkotelnikov commented on src/main/kotlin/ru/tinkoff/fintech/service/notification/NotificationMessageGeneratorImpl.kt
> +            |за категорию ${category}.
когда передаем один параметр, фигурные скобки можно опустить

2020-02-26 07:07 UTC, dkotelnikov approved these changes

2020-02-29 17:59 UTC, merged